##############################
# dein.toml | Made by NULLCT #
##############################
#パッケージ管理ツール
[[plugins]]
repo = 'Shougo/dein.vim'

#カラースキーム
[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  colorscheme onedark
'''

#色々と補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  call deoplete#enable()
'''

#エラー表示(lintちゃんがあれば自動でやってくれる)
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_sign_column_always = 1
  "リスト表示したいなら↓
  "let g:ale_open_list = 1
  let g:ale_keep_list_window_open = 1
  " 保存時に整形してくれる
  let g:ale_fix_on_save = 1
'''

#インデントをわかりやすく
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_color_term = 239
  let g:indentLine_color_gui = '#708090'
  let g:indentLine_char = '|' "use ¦, ┆ or │
'''

#変更点を左側に表示(git使用)
[[plugins]]
repo = 'airblade/vim-gitgutter'

#vimのpowerline
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  set laststatus=2
  "タブ一覧もpowerline
  let g:airline#extensions#tabline#enabled = 1
  "ALEの表示
  let g:airline#extensions#ale#enabled = 1
  "powerline有効
  let g:airline_powerline_fonts = 1
  "テーマをonedarkに
  let g:airline_theme = 'onedark'
  "タブ一覧に数字を表示
  let g:airline#extensions#tabline#buffer_idx_mode = 1
'''

#vim-airlineのカラーテーマ拡張
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#ファイルのアイコンをnerdfontを使って表示
[[plugins]]
repo = 'ryanoasis/vim-devicons'

#vimからgitを操作
[[plugins]]
repo = 'tpope/vim-fugitive'
