###################################
# dein_lazy.toml | Made by NULLCT #
###################################
[[plugins]]
repo = "rhysd/vim-clang-format"
on_ft = ['c', 'cpp']

#C/C++用のdeoplete拡張
[[plugins]]
repo = 'Shougo/deoplete-clangx'
on_ft = ['c', 'cpp']

#C/C++用の拡張ハイライト
[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = ['c', 'cpp']

#python用のdeoplete拡張
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

#Vimでmarkdown書く時用
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']
[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']

#フォルダとかをツリー表示する
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let g:NERDTreeQuitOnOpen=1
  let g:NERDTreeWinSize=20
'''

#C/C++用のinclude補完
[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']

#ショットカット？よう分からん
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star)
  nmap # <Plug>(anzu-sharp)
'''

#強いと噂。ファイルとか一瞬で開ける？
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
'''

#classとか関数と一覧表示できる
[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  "tagbar の設定
  let g:tagbar_width = 20        " 初期設定はwidth=40なのでちょっと幅とりすぎ。
  set fileformats=unix,dos,mac      " エラー防止
  set fileencodings=utf-8,sjis
  nmap <F8> :TagbarToggle<CR>
'''
