[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><Tab> pumvisible() ? "\<DOWN>" : "\<Tab>"
  inoremap <expr><S-Tab> pumvisible() ? "\<UP>" : "\<S-Tab>"
'''

[[plugins]]
repo = 'Shougo/deoplete-clangx'
on_ft = 'c++'

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = 'c++'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = 'c++'
