##############################
# dein.toml | Made by NULLCT #
##############################
#パッケージ管理ツール
[[plugins]]
repo = 'Shougo/dein.vim'

#カラースキーム
[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  colorscheme onedark
'''

#色々と補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  call deoplete#enable()
  let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-3.8/lib/libclang-3.8.so.1'
  let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
'''

#エラー表示(lintちゃんがあれば自動でやってくれる)
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_sign_column_always = 1
  "リスト表示したいなら↓
  "let g:ale_open_list = 1
  let g:ale_keep_list_window_open = 1
  " 保存時に整形してくれる
  let g:ale_fix_on_save = 1
'''

#インデントを強調表示(スペース民用)
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  " Vim 起動時 vim-indent-guides を自動起動
  let g:indent_guides_enable_on_vim_startup=1
  " ガイドをスタートするインデントの量
  let g:indent_guides_start_level=1
  " 自動カラー無効
  let g:indent_guides_auto_colors=0
  " 奇数番目のインデントの色
  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#444433 ctermbg=black
  " 偶数番目のインデントの色
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#333344 ctermbg=darkgray
  " ガイドの幅
  let g:indent_guides_guide_size = 1
'''


#パワーライン。
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
   \ 'colorscheme': 'one',
   \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
   \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" },
   \ 'active': {
   \   'left': [ [ 'mode', 'paste' ],
   \             [ 'readonly', 'filename', 'modified' ],
   \             [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ] ]
   \ },
   \ 'component_function': {
   \   'readonly': 'LightlineReadonly',
   \   'filename': 'LightlineFilename',
   \ },
   \}
'''

#変更点を左側に表示(git使用)
[[plugins]]
repo = 'airblade/vim-gitgutter'

#lightlineにaleのエラー情報を表示するためのツール
[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']
hook_add = '''
let g:lightline.component_expand = {
   \  'linter_checking': 'lightline#ale#checking',
   \  'linter_warnings': 'lightline#ale#warnings',
   \  'linter_errors': 'lightline#ale#errors',
   \  'linter_ok': 'lightline#ale#ok',
   \ }
let g:lightline.component_type = {
   \     'linter_checking': 'left',
   \     'linter_warnings': 'warning',
   \     'linter_errors': 'error',
   \     'linter_ok': 'left',
   \ }
'''
