#Kernel
[[plugins]]
repo = 'Shougo/dein.vim'

#Colorschemes
[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = 'colorscheme gruvbox'

#Status
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
set noshowmode
let g:lightline = {
  \ 'colorscheme': 'gruvbox',
  \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
  \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" },
  \ 'active': { 'left': [ [ 'mode', 'paste' ], [ 'readonly', 'filename', 'modified' ] ] }
  \ }
'''

#Views
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_color_term = 238
  let g:indentLine_char = '│' "use ¦, ┆ or │
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let NERDTreeShowHidden = 1
  let NERDTreeQuitOnOpen = 1
  let g:NERDTreeWinSize=24
  autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
  map <C-n> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
'''

#Complement
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  set termguicolors
  set pumblend=10
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><Tab> pumvisible() ? "\<DOWN>" : "\<Tab>"
  inoremap <expr><S-Tab> pumvisible() ? "\<UP>" : "\<S-Tab>"
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
build = ['./install.sh']
hook_add = '''
  let s:node = empty($XDG_CONFIG_HOME) ? expand('$HOME/.config') : $XDG_CONFIG_HOME
  let g:LanguageClient_serverCommands = {
    \ 'c': ['clangd'],
    \ 'cpp': ['clangd'],
    \ 'python': ['pyls']
    \ }
'''

[[plugins]]
repo = 'cohama/lexima.vim'

#Highlight
[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
hook_add = '''
  let g:cpp_class_scope_highlight = 1
  let g:cpp_member_variable_highlight = 1
  let g:cpp_class_decl_highlight = 1
  let g:cpp_class_decl_highlight = 1
  let g:cpp_experimental_simple_template_highlight = 1
  let g:cpp_concepts_highlight = 1
  let g:cpp_no_function_highlight = 1
'''
